board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.main, name='main'),
    path('interest/', views.survey_interest, name='survey_interest'),
    path('ongoing/', views.survey_ongoing, name='survey_ongoing'),
    path('answer/', views.survey_participated, name='survey_participated'),
    path('complete/', views.survey_complete, name='survey_complete'),
    path('tag/<int:pk>/', views.survey_tag, name='survey_tag'),
]

branchtown/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', lambda r: redirect('main:mainpage'), name='root'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('board/', include('board.urls', namespace='board')),
    path('main/', include('main.urls', namespace='main')),
    path('response/', include('response.urls', namespace='response')),
    path('survey/', include('survey.urls', namespace='survey')),
    path('tag/', include('tag.urls', namespace='tag')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.mainpage, name='mainpage'),
    path('/intro/', views.intropage, name='intropage'),
    path('/cs/', views.cspage, name='cspage'),


]

response/urls.py
from django.urls import path
from . import views


app_name = 'response'

urlpatterns = [
    path('result/<int:pk>/', views.ResultView.as_view(), name="result_survey"),
    path('<int:pk>/preview/', views.preview_survey, name='preview_survey'),
    path('<int:pk>/survey/', views.response_survey, name='response_survey'),
    path('<int:pk>/join/', views.join_survey, name='join_survey'),

    # path('<int:pk>/survey/text/', views.response_survey_text, name='response_survey_text')
]

survey/urls.py
from django.urls import path
from . import views

app_name = "survey"

urlpatterns = [
    path('make/', views.make_survey, name='make_survey'),
    path('make/<int:pk>/', views.make_index, name='make_index'),
    path('make/<int:pk>/choice/', views.make_multiple_choice, name='make_multiple_choice'),
    path('make/<int:pk>/text/', views.make_text_answer, name='make_text_answer'),
    # path('<int:pk>/multiple_choice/', views.multiple_choice, name='multiple_choice'),
    path('<int:pk>/results/', views.results, name='results'),
    path('mysurvey/', views.my_survey, name='my_survey'),
    path('mysurvey/<int:pk>/', views.my_survey_detail, name='my_survey_detail'),
    path('mysurvey/<int:pk>/complete/', views.my_survey_complete, name='my_survey_complete'),
]

tag/urls.py
from django.urls import path

app_name = 'tag'

urlpatterns = [

]

survey/models.py
from django.db import models
from django.conf import settings
from tag.models import Tag


class Survey(models.Model):
    STATUS_CHOICES = (
        ('o', 'ongoing'),
        ('c', 'complete'),
        # TODO 다른 다양한 status 추가
    )
    title = models.CharField(max_length=100)
    subtitle = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)
    tag = models.ManyToManyField(Tag)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    response_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Field(models.Model):
    FIELD_TYPE = (
        ('1', '객관식'),
        ('2', '주관식'),
        ('3', '단답식'),
    )
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    type = models.CharField(max_length=10, choices=FIELD_TYPE)
    question = models.CharField(max_length=100)

    def __str__(self):
        return self.question


class MultipleChoice(models.Model):
    field = models.ForeignKey(Field, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class TextAnswer(models.Model):
    field = models.ForeignKey(Field, on_delete=models.CASCADE)
    answer = models.TextField()

    def __str__(self):
        return self.answer

#
#
# class Response(models.Model):
#     respondent = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
#     created_at = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return self.respondent

survey/forms.py
from django import forms
from django.forms import modelformset_factory
from tag.models import Tag
from .models import Survey, Field, MultipleChoice


class SurveyForm(forms.ModelForm):
    class Meta:
        model = Survey
        fields = ('title', 'subtitle',)

    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple(), )

    def __init__(self, *args, **kwargs):
        # Only in case we build the form from an instance
        # (otherwise, 'toppings' list should be empty)
        if kwargs.get('instance'):
            # We get the 'initial' keyword argument or initialize it
            # as a dict if it didn't exist.
            initial = kwargs.setdefault('initial', {})
            # The widget for a ModelMultipleChoiceField expects
            # a list of primary key for the selected data.
            initial['tags'] = [t.pk for t in kwargs['instance'].tag_set.all()]

        forms.ModelForm.__init__(self, *args, **kwargs)

    def save(self, commit=True):
        # Get the unsave Pizza instance
        instance = forms.ModelForm.save(self, False)

        # Prepare a 'save_m2m' method for the form,
        old_save_m2m = self.save_m2m

        def save_m2m():
            old_save_m2m()
            # This is where we actually link the pizza with toppings
            instance.tag_set.clear()
            instance.tag_set.add(*self.cleaned_data['tags'])

        self.save_m2m = save_m2m

        # Do we need to save all changes now?
        if commit:
            instance.save()
            self.save_m2m()

        return instance


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = MultipleChoice
        fields = '__all__'


class ChoiceIssueForm(forms.Form):
    Issue = forms.CharField()


class FieldForm(forms.ModelForm):
    class Meta:
        model = Field
        fields = ('question',)   # 'type',


ChoiceFormSet = modelformset_factory(
    MultipleChoice,
    fields=['choice_text'],
    extra=1,
    widgets={
        'choice_text': forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter choice text',
            }
        )
    }
)


class TextAnswerForm(forms.ModelForm):
    class Meta:
        model = Field
        fields = ['question']

survey/views.py
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, redirect, get_object_or_404
from .models import Survey, Field, MultipleChoice
from .forms import SurveyForm, FieldForm, ChoiceFormSet

@login_required
def make_survey(request):
    if request.method == "POST":
        form = SurveyForm(request.POST, request.FILES)
        if form.is_valid():
            survey = form.save(commit=False)
            survey.author = request.user
            survey.status = 'o'     # TODO: 일단 'o' 로 설정, 추후에 model 에 status 추가 후 값 변경해야함
            survey.save()
            survey_instance = Survey.objects.get(pk=survey.pk)
            survey_instance.tag.add(*form.cleaned_data['tags'])
            return redirect('survey:make_index', survey.pk)
    else:
        form = SurveyForm()

    return render(request, 'survey/make_survey.html', {
        'form': form,
    })

@login_required
def make_index(request, pk):
    survey = Survey.objects.get(pk=pk)
    if request.user == survey.author:
        field_list = survey.field_set.all()
        context = {
            'survey': survey,
            'field_list': field_list,
        }
        return render(request, 'survey/make_index.html', context)
    else:
        return redirect('root')
        # TODO: 설문 작성자와 user 가 동일하지 않을 경우, 일단 root 로 redirect


def make_multiple_choice(request, pk):
    survey = Survey.objects.get(pk=pk)
    if request.user == survey.author:
        if request.method == "POST":
            field_form = FieldForm(request.POST)
            formset = ChoiceFormSet(request.POST)
            if field_form.is_valid() and formset.is_valid():
                field = field_form.save(commit=False)
                field.survey = survey
                field.type = '1'
                field.save()
                for form in formset:
                    choice = form.save(commit=False)
                    choice.field = field
                    choice.save()
                return redirect('survey:make_index', pk)
        else:
            field_form = FieldForm()
            formset = ChoiceFormSet(queryset=MultipleChoice.objects.none())
        return render(request, 'survey/make_choice.html', {
            'field_form': field_form,
            'formset': formset,
        })
    else:
        return redirect('root')
        # TODO: 설문 작성자와 user 가 동일하지 않을 경우, 일단 root 로 redirect



def make_text_answer(request, pk):
    survey = Survey.objects.get(pk=pk)
    if request.user == survey.author:
        if request.method == "POST":
            form = FieldForm(request.POST)     # TODO: Field Form 과 차이점 X,
            if form.is_valid():
                field = form.save(commit=False)
                field.survey = survey
                field.type = '3'
                field.save()
                return redirect('survey:make_index', pk)
        else:
            form = FieldForm()
        return render(request, 'survey/make_text_answer.html', {
            'survey': survey,
            'form': form,
        })
    else:
        return redirect('root')
        # TODO: 설문 작성자와 user 가 동일하지 않을 경우, 일단 root 로 redirect


@login_required
def make_field(request, pk):
    if request.method == "POST":
        form = FieldForm(request.POST, request.FILES)
        if form.is_valid():
            field = form.save(commit=False)
            field.survey = Survey.objects.get(pk=pk)
            field.save()
            return redirect('/board/')
    else:
        form = FieldForm()

    return render(request, 'survey/make_field_txt.html', {
        'field': form,
    })



def multiple_choice(request, pk):
    if request.method == "POST":
        choiceformset = ChoiceFormSet(request.POST)
        if choiceformset.is_valid():
            return redirect('survey:make_index', pk)
# >>>>>>> 030893919c333c217b4815b5dd7179e044ea3329
#     field = get_object_or_404(Field, pk=pk)
#     try:
#         selected_choice = field.multiplechoice_set.get(pk=request.POST['multiple_choice'])
#     except (KeyError, MultipleChoice.DoesNotExist):
#         return render(request, 'survey/make_field_mul.html', {'field': field,
#                                                                'error_message':
#                                                                "You didn't select a choice", })
#     else:
#         selected_choice += 1
#         selected_choice.save()
#         return HttpResponseRedirect(reverse('survey:results', args=field.id,))


def make_field_txt(request, pk):
    field = get_object_or_404(Field, pk=pk)
    try:
        text_answer = field.textanswer_set.all()
    except (KeyError, text_answer.DoesNotExist):
        return render(request, 'survey/make_field_txt.html', {'field': field,
                                                               'error_message':
                                                               "You didn't write answer", })
    else:
        return redirect('survey:make_index', field.pk)
# =======
# def multiple_choice(request, pk):
#     if request.method == "POST":
#         choiceformset = ChoiceFormSet(request.POST)
#         if choiceformset.is_valid():
#             return redirect('survey:make_index', pk)
#     else:
#         data = {
#             'form-TOTAL_FORMS': '1',
#             'form-INITIAL_FORMS': '1',
#             'form-MAX_NUM_FORMS': '10',
#         }
#         choiceformset = ChoiceFormSet(data)
#     return render(request, 'survey/choice.html', {
#         'survey': Survey.objects.get(pk=pk),
#         'choiceformset': choiceformset,
#     })
# >>>>>>> 030893919c333c217b4815b5dd7179e044ea3329


def results(request, pk):
    field = get_object_or_404(Field, pk=pk)
    return render(request, 'survey/results.html', {'field': field})


@login_required()
def my_survey(request):
    user = request.user
    surveys = Survey.objects.filter(author=user)
    return render(request, 'survey/my_survey.html', {
        'surveys': surveys,
    })


@login_required()
def my_survey_detail(request, pk):
    survey = get_object_or_404(Survey, pk=pk)
    if survey.author == request.user:
        return render(request, 'survey/my_survey_detail.html', {
            'survey': survey,
        })
    else:
        return redirect('root')     # TODO: 일단 root 로 이동


@login_required()
def my_survey_complete(request, pk):
    survey = get_object_or_404(Survey, pk=pk)
    if survey.author == request.user:
        survey.status = 'c'
        survey.save()
        return render(request, 'survey/my_survey_complete.html', {
            'survey': survey,
        })
    else:
        return redirect('root')     # TODO: 일단 root 로 이동

survey/templates/survey/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<form action="{% url 'survey:vote' question.id %}" method="post">
    {%  csrf_token %}
        {%  for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}
    <input type="submit" value="응답 제출"/>
</form>

survey/templates/survey/index.html
{% if latest_question_list %}

    <ul>
        {%  for question in latest_question_list %}
            <li><a href="/survey/{{ question.id }}/">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No surveys are available</p>
{% endif %}

survey/templates/survey/make_choice.html
{#{% extends 'layout.html' %}#}
{% load bootstrap4 %}
{% bootstrap_css %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'survey/css/style.css'%}">
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="survey-title" style="font-family : '나눔스퀘어 Light'; color : #af8c53; margin-top : 80px;">Multiple Choice Question</h1>
        <hr style="width : 500px; margin-bottom : 50px; "/>

        <form class="form-horizontal" method="POST" action="">
            {% csrf_token %}
            {% bootstrap_form field_form %}

            <div class="input-group-append">
                <input type="button" class="btn btn-success" id="add_more" value="+add">
                <input type="button" class="btn btn-danger" id="remove" value="-remove">
            </div>

            {{ formset.management_form }}
            {% for form in formset %}
            <div class="row form-row form-horizontal" id="form_set">
                <div class="col-12 choice-text">
                    {% bootstrap_form form %}
                </div>
            </div>
            {% endfor %}

            <div id="empty_form" style="display:none">
                <div class="col-12 choice-text">
                    {% bootstrap_form formset.empty_form %}
        {#            {{ formset.empty_form.as_table }}#}
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <button type="submit" class="btn btn-primary add-question">Add Question</button>
                </div>
            </div>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
                crossorigin="anonymous">
    </script>

    <script type='text/javascript'>
        $(document).ready(function() {
            $('#add_more').click(function(){
                var form_idx=$('#id_form-TOTAL_FORMS').val();
                $('#form_set')
                    .append(
                        $('#empty_form')
                            .html()
                            .replace(/__prefix__/g, form_idx)
                    );
                $('#id_form-TOTAL_FORMS').val(parseInt(form_idx)+1);
                {#console.log(form_idx);#}
            });
        });

        $(document).ready(function() {
            $('#remove').click(function(){
                var form_idx=$('#id_form-TOTAL_FORMS').val();
                if (form_idx > 1) {
                    $('#form_set>div:last-child').remove();
                    $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) - 1);
                }
                {#console.log(form_idx);#}
            });
        });
    </script>
{% endblock %}

survey/templates/survey/make_field_mul.html
{% block content %}
    <div class="container">
        <h1 class="survey-title" style=" margin-top : 80px;">{{ field.question }}</h1>
        <hr style="width : 300px; margin-bottom : 50px;"/>

        {% if errr_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <form action="{% url 'survey:vote' question.id %}" method="post">
            {%  csrf_token %}
                {%  for choice in field.choice_set.all %}
                    <input type="radio" name="choose" id="choose{{ forloop.counter }}" value="{{ choice.id }}" />
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
                {% endfor %}
            <input type="submit" value="응답 제출"/>
        </form>
    </div>
{% endblock %}

survey/templates/survey/make_field_txt.html
{% load bootstrap4 %}
{% bootstrap_css %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <script src=https://code.jquery.com/jquery-3.3.1.min.js integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="crossorigin="anonymous"></script>

    </head>
    <body>


        </body>
</html>

survey/templates/survey/make_index.html
{% extends 'layout.html' %}
{% load static %}
{% block style %}
    <link rel="stylesheet" href="{% static 'survey/css/style.css'%}">
{% endblock %}
{% block content %}

    <div class="container">
        <h1 class="survey-title" style="font-family : '나눔스퀘어 Light'; color : #af8c53; margin-top : 80px;">{{ survey.title }}</h1>
        <hr style="width : 500px; margin-bottom : 50px;"/>

        <div class="cont-center">
            <a href="{% url 'survey:make_multiple_choice' survey.id %}"><button type="submit" class="btn btn-primary add-button">
                multi-choice
            </button></a>
            <button type="submit" class="btn btn-primary add-button"><a href="{% url 'survey:make_text_answer' survey.id %}">
                text-answer
            </a></button>
            <hr>
            <table class="table table-bordered">
                <thead>
                    <tr class="cont">
                        <th scope="col" width="150">#</th>
                        <th scope="col" width="150">Type</th>
                        <th scope="col">Question</th>
                    </tr>
                </thead>
                 <tbody>
                    {% for field in field_list %}
                        <tr>
                            <td>{{ forloop.counter }}번</td>
                            <td>
                                {% if field.type == '1' %}
                                    multiple choice
                                {% else %}
                                    text answer
                                {% endif %}
                            </td>
                            <td>
                                {{ field.question }}
    {#                            {% if field.type == '1' %}#}
    {#                                <i>(선지 list#}
    {#                                    {% for choice in field.multiplechoice_set.all %}#}
    {#                                        {{ choice }}/#}
    {#                                    {% endfor %})#}
    {#                                </i>#}
    {#                            {% endif %}#}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <button type="submit" class="btn btn-primary add-button" id="submit-survey"><a href="{% url 'board:main' %}" >Create</a></button>
    </div>

    <script>
    $(function() {
        $("#submit-survey").on('click', function () {
            alert("Survey was successfully created!")
        });
    });
    </script>
{% endblock %}

survey/templates/survey/make_survey.html
{% extends 'layout.html' %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}

{% block style %}
    <link rel="stylesheet" href="{% static 'survey/css/style.css'%}">
{% endblock %}

{% block content %}
    <div class="container" >
        <h1 class="survey-title" style="font-family : '나눔스퀘어 Light'; color: #af8c53; margin-top : 80px;">Create Your Own Survey Form</h1>
        <hr style="width : 700px; margin-bottom : 50px;"/>
        <div class="survey-box" style="width:900px;">
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-primary" id="create-button" value="Next">
            </form>
    </div>
    </div>
{% endblock %}

survey/templates/survey/make_text_answer.html
{% extends 'layout.html' %}
{% load static %}
{% load bootstrap4 %}
{% block style %}
    <link rel="stylesheet" href="{% static 'survey/css/style.css'%}">
{% endblock %}
{% bootstrap_css %}
{% block content %}
    <div class="container">
        <h1 class="survey-title" style="font-family: '나눔스퀘어 Light'; color : #af8c53; margin-top : 80px;">TextAnswer Question</h1>
        <hr style="width : 500px; margin-bottom : 50px;"/>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary add-question" value="Add Question">
        </form>
    </div>
{% endblock %}

survey/templates/survey/my_survey.html
{% extends 'layout.html' %}
{%  load static %}
{%  block style %}
    <link rel="stylesheet" href="{% static 'survey/css/mysurvey.css' %}">
{%  endblock %}

{% block content %}
    <div class="MySurveyTitle">
        <p> My Survey</p>
    </div>
    <div class="container">
        <div class="row">
            {% for survey in surveys %}
                <div class="col-12 col-md-6 col-lg-4 col-xl-3">
                    <div class="card">
                        <img src="{% static 'board/images/test5.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <div id="board_titles">
                                <p class="card-title">{{ survey.title }}</p>
                                <p class="card-text">S{{  survey.subtitle  }}</p>
                            </div>
                            <div id="board_tags">
                            <p>
                                {% for tag in  survey.tag.all %}
                                    <a href="{% url 'board:survey_tag' tag.id %}" style="text-decoration: none">
                                        #{{ tag }}
                                    </a>
                                {% endfor %}
                            </p>
                            </div>
                            <div class="board_buttons">
                            <a href="{% url 'survey:my_survey_complete' survey.id %}" class="complete_button">Complete</a>
                            <a href="{% url 'response:result_survey' survey.id %}" class="result_button">View Results</a>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

survey/templates/survey/my_survey_complete.html
{% extends 'layout.html' %}
{%  load static %}
{%  block style  %}
    <link rel="stylesheet" href="{% static 'survey/css/mysurvey.css' %}">
{%  endblock %}

{% block content %}
    <div class="container" style="font-family: '나눔스퀘어 Light', serif; vertical-align: middle; height: 600px; line-height: 600px; text-align: center;">
        <div class="previewTitle" style="background-color: #fbfbfb; display: inline-block; vertical-align: middle; line-height: normal; height: 450px; width: 750px; padding: 50px;">
            <div class="previewImage" style="margin-bottom: 20px;"><img src="{% static 'response/images/quotation.png' %}" width="30" height="30"></div>
            <h1 class="previewTitle" style="margin-bottom: 10px;">{{ survey.title }}</h1>
            <h1> 설문이 종료되었습니다. </h1>
            <hr style="width: 500px; margin-bottom: 50px;">
            <div class="previewButton">
                <a href="{% url 'survey:my_survey' %}" style="background-color: #c4a784; padding: 15px; border-radius: 10px; color: white;">Confirm</a>
                <a href="{% url 'survey:my_survey' %}" style="background-color: #c4a784; padding: 15px; border-radius: 10px; color: white; display: inline-block; width: 100px;">Cancel</a>
            </div>
        </div>
    </div>
{% endblock %}

survey/templates/survey/my_survey_detail.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <ul>
            <li>제목 : {{ survey.title }}</li>
            <li>내용 : {{ survey.subtitle }}</li>
            <li>작성자 : {{ survey.author }}</li>
            <li>태그 :
                {% for tag in survey.tag.all %}
                    #{{ tag }}
                {% endfor %}
            </li>
            <li>상태 :
                {% if survey.status == 'o' %}
                    진행중
                {% else %}
                    종료
                {% endif %}
            </li>
            <li>응답수 : {{ survey.response_count }}</li>
        </ul>
        <a href="{% url 'survey:my_survey_complete' survey.id %}" class="btn btn-danger">설문 종료</a>
    </div>
{% endblock %}

survey/templates/survey/results.html
<h1>{{ field.question }}</h1>

<ul>
    {% for choice in field.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {%  endfor %}
</ul>

<a href="{% url 'survey:multiple_choice' field.id %}">Vote again?</a>