board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.main, name='main'),
    path('interest/', views.survey_interest, name='survey_interest'),
    path('ongoing/', views.survey_ongoing, name='survey_ongoing'),
    path('answer/', views.survey_participated, name='survey_participated'),
    path('complete/', views.survey_complete, name='survey_complete'),
    path('tag/<int:pk>/', views.survey_tag, name='survey_tag'),
]

branchtown/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', lambda r: redirect('main:mainpage'), name='root'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('board/', include('board.urls', namespace='board')),
    path('main/', include('main.urls', namespace='main')),
    path('response/', include('response.urls', namespace='response')),
    path('survey/', include('survey.urls', namespace='survey')),
    path('tag/', include('tag.urls', namespace='tag')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.mainpage, name='mainpage'),
    path('/intro/', views.intropage, name='intropage'),
    path('/cs/', views.cspage, name='cspage'),


]

survey/urls.py
from django.urls import path
from . import views

app_name = "survey"

urlpatterns = [
    path('make/', views.make_survey, name='make_survey'),
    path('make/<int:pk>/', views.make_index, name='make_index'),
    path('make/<int:pk>/choice/', views.make_multiple_choice, name='make_multiple_choice'),
    path('make/<int:pk>/text/', views.make_text_answer, name='make_text_answer'),
    # path('<int:pk>/multiple_choice/', views.multiple_choice, name='multiple_choice'),
    path('<int:pk>/results/', views.results, name='results'),
    path('mysurvey/', views.my_survey, name='my_survey'),
    path('mysurvey/<int:pk>/', views.my_survey_detail, name='my_survey_detail'),
    path('mysurvey/<int:pk>/complete/', views.my_survey_complete, name='my_survey_complete'),
]

tag/urls.py
from django.urls import path

app_name = 'tag'

urlpatterns = [

]

branchtown/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}BranchTown{% endblock %}</title>

    <script src="https:/ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/script.js' %}"></script>


    {% block style %}{% endblock %}
</head>

<body style="font-family : '나눔스퀘어';">
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top" style="padding-left : 0;">
    <div class="container-fluid" >
        <a class="navbar-brand" href="{% url 'root' %}" style="padding-top: 0; padding-bottom : 0;">
            <img src="{% static 'images/logo.jpg' %}" alt="#" width="230" class="logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive" style="font-family : 나눔스퀘어;">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" style="color: #af8c53;" href="{% url 'main:intropage' %}" >Introduction</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style=" color : #af8c53;" href="{% url 'survey:make_survey' %}" >Survey Form</a>
                </li>

                <li class="nav-item dropdown">
                  <a href="#" class="dropdown-toggle nav-link" style=" color : #af8c53;" href="#"  data-toggle="dropdown" role="button" aria-expanded="false">Survey board <span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'board:main' %}" style="font-size : 16px; margin-left :0; color : gray;">All Survey</a></li>
                            <div class="dropdown-divider"></div>
                            <li><a href="{% url 'board:survey_interest' %}" style="font-size : 16px; margin-left :0; color : gray;">Recommended</a></li>
                            <li><a href="{% url 'board:survey_participated' %}" style="font-size : 16px; margin-left :0; color : gray;">Participated</a></li>
                            <div class="dropdown-divider"></div>
                            <li><a href="{% url 'board:survey_ongoing' %}" style="font-size : 16px; margin-left :0; color : gray;">Ongoing</a></li>
                            <li><a href="{% url 'board:survey_complete' %}" style="font-size : 16px; margin-left :0; color : gray;">Completed</a></li>
                      </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style=" color : #af8c53;" href="{% url 'main:cspage' %}" >Contact</a>
                </li>

                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'signup' %}" class="nav-link" style=" color : #af8c53;">Join</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'login' %}?next={{ request.path }}" class="nav-link" style=" color : #af8c53;">Login</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'profile' %}" class="nav-link" style=" color : #af8c53;">My Page</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'logout' %}?next={{ request.path }}" class="nav-link" style=" color : #af8c53;">Logout</a>
                    </li>
                {% endif %}
            </ul>

        </div>
    </div>
</nav>


    {% block content %}
    {% endblock %}


    <button class="to-top-btn">
        <img src="{% static 'images/arrows.jpg' %}" width="32" height="32">
    </button>
    <!-- footer -->
    <div id="footer" style="display :block; width : 100%; height : 80px; margin-left : auto; margin-right : auto;">
            <p class="text-muted">
            <br/>
            ⓒ BranchTown 2019<br/>
              Survey platform for college students
            </p>
    </div>



</body>
</html>