branchtown/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', lambda r: redirect('main:mainpage'), name='root'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('board/', include('board.urls', namespace='board')),
    path('main/', include('main.urls', namespace='main')),
    path('response/', include('response.urls', namespace='response')),
    path('survey/', include('survey.urls', namespace='survey')),
    path('tag/', include('tag.urls', namespace='tag')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.mainpage, name='mainpage'),
    path('/intro/', views.intropage, name='intropage'),
    path('/cs/', views.cspage, name='cspage'),


]

response/urls.py
from django.urls import path
from . import views


app_name = 'response'

urlpatterns = [
    path('result/<int:pk>/', views.ResultView.as_view(), name="result_survey"),
    path('<int:pk>/preview/', views.preview_survey, name='preview_survey'),
    path('<int:pk>/survey/', views.response_survey, name='response_survey'),
    path('<int:pk>/join/', views.join_survey, name='join_survey'),

    # path('<int:pk>/survey/text/', views.response_survey_text, name='response_survey_text')
]

survey/urls.py
from django.urls import path
from . import views

app_name = "survey"

urlpatterns = [
    path('make/', views.make_survey, name='make_survey'),
    path('make/<int:pk>/', views.make_index, name='make_index'),
    path('make/<int:pk>/choice/', views.make_multiple_choice, name='make_multiple_choice'),
    path('make/<int:pk>/text/', views.make_text_answer, name='make_text_answer'),
    # path('<int:pk>/multiple_choice/', views.multiple_choice, name='multiple_choice'),
    path('<int:pk>/results/', views.results, name='results'),
    path('mysurvey/', views.my_survey, name='my_survey'),
    path('mysurvey/<int:pk>/', views.my_survey_detail, name='my_survey_detail'),
    path('mysurvey/<int:pk>/complete/', views.my_survey_complete, name='my_survey_complete'),
]

tag/urls.py
from django.urls import path

app_name = 'tag'

urlpatterns = [

]

response/models.py
from django.db import models
from django.conf import settings
from survey.models import Survey


class Response(models.Model):
    respondent = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        return str(self.respondent)

survey/models.py
from django.db import models
from django.conf import settings
from tag.models import Tag


class Survey(models.Model):
    STATUS_CHOICES = (
        ('o', 'ongoing'),
        ('c', 'complete'),
        # TODO 다른 다양한 status 추가
    )
    title = models.CharField(max_length=100)
    subtitle = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)
    tag = models.ManyToManyField(Tag)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    response_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Field(models.Model):
    FIELD_TYPE = (
        ('1', '객관식'),
        ('2', '주관식'),
        ('3', '단답식'),
    )
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    type = models.CharField(max_length=10, choices=FIELD_TYPE)
    question = models.CharField(max_length=100)

    def __str__(self):
        return self.question


class MultipleChoice(models.Model):
    field = models.ForeignKey(Field, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class TextAnswer(models.Model):
    field = models.ForeignKey(Field, on_delete=models.CASCADE)
    answer = models.TextField()

    def __str__(self):
        return self.answer

#
#
# class Response(models.Model):
#     respondent = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
#     created_at = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return self.respondent

response/forms.py
from django import forms
from django.forms import modelformset_factory

from survey.models import TextAnswer


TextAnswerFormSet = modelformset_factory(
    TextAnswer,
    fields=['answer'],
    widgets={
        'answer': forms.Textarea(
            attrs={
                # 'class': 'form-control',
                'placeholder': 'Enter your answer',
            }
        )
    }
)


class TextAnswerForm(forms.ModelForm):
    class Meta:
        model = TextAnswer
        fields = ['field', 'answer']

survey/forms.py
from django import forms
from django.forms import modelformset_factory
from tag.models import Tag
from .models import Survey, Field, MultipleChoice


class SurveyForm(forms.ModelForm):
    class Meta:
        model = Survey
        fields = ('title', 'subtitle',)

    tags = forms.ModelMultipleChoiceField(queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple(), )

    def __init__(self, *args, **kwargs):
        # Only in case we build the form from an instance
        # (otherwise, 'toppings' list should be empty)
        if kwargs.get('instance'):
            # We get the 'initial' keyword argument or initialize it
            # as a dict if it didn't exist.
            initial = kwargs.setdefault('initial', {})
            # The widget for a ModelMultipleChoiceField expects
            # a list of primary key for the selected data.
            initial['tags'] = [t.pk for t in kwargs['instance'].tag_set.all()]

        forms.ModelForm.__init__(self, *args, **kwargs)

    def save(self, commit=True):
        # Get the unsave Pizza instance
        instance = forms.ModelForm.save(self, False)

        # Prepare a 'save_m2m' method for the form,
        old_save_m2m = self.save_m2m

        def save_m2m():
            old_save_m2m()
            # This is where we actually link the pizza with toppings
            instance.tag_set.clear()
            instance.tag_set.add(*self.cleaned_data['tags'])

        self.save_m2m = save_m2m

        # Do we need to save all changes now?
        if commit:
            instance.save()
            self.save_m2m()

        return instance


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = MultipleChoice
        fields = '__all__'


class ChoiceIssueForm(forms.Form):
    Issue = forms.CharField()


class FieldForm(forms.ModelForm):
    class Meta:
        model = Field
        fields = ('question',)   # 'type',


ChoiceFormSet = modelformset_factory(
    MultipleChoice,
    fields=['choice_text'],
    extra=1,
    widgets={
        'choice_text': forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter choice text',
            }
        )
    }
)


class TextAnswerForm(forms.ModelForm):
    class Meta:
        model = Field
        fields = ['question']

response/views.py
import json

from django.forms import formset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.safestring import mark_safe
from django.views.generic import View
from django.contrib.auth import get_user_model

from response.forms import TextAnswerForm
from response.models import Response
from survey.models import Survey, Field, MultipleChoice, TextAnswer

User = get_user_model()

class ResultView(View):
    def get(self, request, pk=4):
        survey = Survey.objects.get(pk=pk)


        #전체를 순회할 데이터 set
        fields = Field.objects.filter(
            survey__id=pk
        )

        field_data = {}
        for field in fields:
            field_data[field.id] = {'type': field.type, 'question': field.question}


        #주/단답식 결과 출력
        txt_fields = Field.objects.filter(
            survey__id=pk, type=2|3
        )

        txt_data = {}
        for field in txt_fields:
            txt_data[field.id] = {'question': field.question, 'answer': []}
            for answer in field.textanswer_set.all():
                txt_data[field.id]['answer'].append(answer.answer)


        print(txt_data)

        #객관식 결과 출력
        multi_fields = Field.objects.filter(
            survey__id=pk, type=1
        )

        multi_data = {}
        for field in multi_fields:
            multi_data[field.id] = {'question': field.question, 'labels': [], 'votes': []}
            for choice in field.multiplechoice_set.all():
                multi_data[field.id]['labels'].append(choice.choice_text)
                multi_data[field.id]['votes'].append(choice.votes)


        return render(request, 'response/charts.html',
                      context={
                          'survey': survey,

                          'json_graphs': mark_safe(json.dumps(multi_data)),
                          'graphs': multi_data,

                          'json_txt': mark_safe(json.dumps(txt_data)),
                          'json_fields': mark_safe(json.dumps(field_data)),

                          'txt': txt_data,
                          'fields': field_data,

                      })


def preview_survey(request, pk):
    survey = get_object_or_404(Survey, pk=pk)
    return render(request, 'response/preview.html', {
        'survey': survey,
    })


def response_survey(request, pk):
    survey = Survey.objects.get(pk=pk)
    fields = survey.field_set.all()
    if request.method == 'POST':
        for field in fields:
            if field.type == '3':
                if request.POST.get('%d' % field.id):
                    answer = TextAnswer.objects.create(field=field, answer=request.POST.get('%d' % field.id))
            elif field.type == '1':
                if request.POST.get('%d' % field.id):
                    choice = MultipleChoice.objects.get(pk=request.POST.get('%d' % field.id))
                    choice.votes += 1
                    choice.save()
        return redirect('response:join_survey', pk)
    return render(request, 'response/survey.html', {
        'survey': survey,
        'fields': fields,
    })



def join_survey(request, pk):
    survey = Survey.objects.get(pk=pk)
    if request.user.is_authenticated:
        respondent = Response.objects.create(respondent=request.user, survey=survey)
    survey.response_count += 1
    survey.save()
    return render(request, 'response/join_survey.html', {
        'survey': survey,
    })

survey/views.py
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, redirect, get_object_or_404
from .models import Survey, Field, MultipleChoice
from .forms import SurveyForm, FieldForm, ChoiceFormSet

@login_required
def make_survey(request):
    if request.method == "POST":
        form = SurveyForm(request.POST, request.FILES)
        if form.is_valid():
            survey = form.save(commit=False)
            survey.author = request.user
            survey.status = 'o'     # TODO: 일단 'o' 로 설정, 추후에 model 에 status 추가 후 값 변경해야함
            survey.save()
            survey_instance = Survey.objects.get(pk=survey.pk)
            survey_instance.tag.add(*form.cleaned_data['tags'])
            return redirect('survey:make_index', survey.pk)
    else:
        form = SurveyForm()

    return render(request, 'survey/make_survey.html', {
        'form': form,
    })

@login_required
def make_index(request, pk):
    survey = Survey.objects.get(pk=pk)
    if request.user == survey.author:
        field_list = survey.field_set.all()
        context = {
            'survey': survey,
            'field_list': field_list,
        }
        return render(request, 'survey/make_index.html', context)
    else:
        return redirect('root')
        # TODO: 설문 작성자와 user 가 동일하지 않을 경우, 일단 root 로 redirect


def make_multiple_choice(request, pk):
    survey = Survey.objects.get(pk=pk)
    if request.user == survey.author:
        if request.method == "POST":
            field_form = FieldForm(request.POST)
            formset = ChoiceFormSet(request.POST)
            if field_form.is_valid() and formset.is_valid():
                field = field_form.save(commit=False)
                field.survey = survey
                field.type = '1'
                field.save()
                for form in formset:
                    choice = form.save(commit=False)
                    choice.field = field
                    choice.save()
                return redirect('survey:make_index', pk)
        else:
            field_form = FieldForm()
            formset = ChoiceFormSet(queryset=MultipleChoice.objects.none())
        return render(request, 'survey/make_choice.html', {
            'field_form': field_form,
            'formset': formset,
        })
    else:
        return redirect('root')
        # TODO: 설문 작성자와 user 가 동일하지 않을 경우, 일단 root 로 redirect



def make_text_answer(request, pk):
    survey = Survey.objects.get(pk=pk)
    if request.user == survey.author:
        if request.method == "POST":
            form = FieldForm(request.POST)     # TODO: Field Form 과 차이점 X,
            if form.is_valid():
                field = form.save(commit=False)
                field.survey = survey
                field.type = '3'
                field.save()
                return redirect('survey:make_index', pk)
        else:
            form = FieldForm()
        return render(request, 'survey/make_text_answer.html', {
            'survey': survey,
            'form': form,
        })
    else:
        return redirect('root')
        # TODO: 설문 작성자와 user 가 동일하지 않을 경우, 일단 root 로 redirect


@login_required
def make_field(request, pk):
    if request.method == "POST":
        form = FieldForm(request.POST, request.FILES)
        if form.is_valid():
            field = form.save(commit=False)
            field.survey = Survey.objects.get(pk=pk)
            field.save()
            return redirect('/board/')
    else:
        form = FieldForm()

    return render(request, 'survey/make_field_txt.html', {
        'field': form,
    })



def multiple_choice(request, pk):
    if request.method == "POST":
        choiceformset = ChoiceFormSet(request.POST)
        if choiceformset.is_valid():
            return redirect('survey:make_index', pk)
# >>>>>>> 030893919c333c217b4815b5dd7179e044ea3329
#     field = get_object_or_404(Field, pk=pk)
#     try:
#         selected_choice = field.multiplechoice_set.get(pk=request.POST['multiple_choice'])
#     except (KeyError, MultipleChoice.DoesNotExist):
#         return render(request, 'survey/make_field_mul.html', {'field': field,
#                                                                'error_message':
#                                                                "You didn't select a choice", })
#     else:
#         selected_choice += 1
#         selected_choice.save()
#         return HttpResponseRedirect(reverse('survey:results', args=field.id,))


def make_field_txt(request, pk):
    field = get_object_or_404(Field, pk=pk)
    try:
        text_answer = field.textanswer_set.all()
    except (KeyError, text_answer.DoesNotExist):
        return render(request, 'survey/make_field_txt.html', {'field': field,
                                                               'error_message':
                                                               "You didn't write answer", })
    else:
        return redirect('survey:make_index', field.pk)
# =======
# def multiple_choice(request, pk):
#     if request.method == "POST":
#         choiceformset = ChoiceFormSet(request.POST)
#         if choiceformset.is_valid():
#             return redirect('survey:make_index', pk)
#     else:
#         data = {
#             'form-TOTAL_FORMS': '1',
#             'form-INITIAL_FORMS': '1',
#             'form-MAX_NUM_FORMS': '10',
#         }
#         choiceformset = ChoiceFormSet(data)
#     return render(request, 'survey/choice.html', {
#         'survey': Survey.objects.get(pk=pk),
#         'choiceformset': choiceformset,
#     })
# >>>>>>> 030893919c333c217b4815b5dd7179e044ea3329


def results(request, pk):
    field = get_object_or_404(Field, pk=pk)
    return render(request, 'survey/results.html', {'field': field})


@login_required()
def my_survey(request):
    user = request.user
    surveys = Survey.objects.filter(author=user)
    return render(request, 'survey/my_survey.html', {
        'surveys': surveys,
    })


@login_required()
def my_survey_detail(request, pk):
    survey = get_object_or_404(Survey, pk=pk)
    if survey.author == request.user:
        return render(request, 'survey/my_survey_detail.html', {
            'survey': survey,
        })
    else:
        return redirect('root')     # TODO: 일단 root 로 이동


@login_required()
def my_survey_complete(request, pk):
    survey = get_object_or_404(Survey, pk=pk)
    if survey.author == request.user:
        survey.status = 'c'
        survey.save()
        return render(request, 'survey/my_survey_complete.html', {
            'survey': survey,
        })
    else:
        return redirect('root')     # TODO: 일단 root 로 이동

response/templates/response/charts.html
{% extends 'response/layout.html' %}
{% load static %}

{#기존에 있던 js.html, css.html, bootstrap_defaults.html을 합침.#}



{% block content %}
{% include 'response/base/js.html' %}
<script>
$(document).ready(function(){
    var defaultData = [];
    var labels = [];

    var json_fields = {{  json_fields }};
    var json_txt = {{ json_txt }};
    var json_graph = {{  json_graphs }};


    for (var id in json_fields) {
        if (json_fields[id].type==1){
            setChart(id);
        }else {
            setList(id);
        }
    }


    function setList(txt_id) {
        document.getElementById("list" + txt_id).innerHTML=": "+json_txt[txt_id].answer
        console.log(json_txt[txt_id].answer)

    }


    function  setChart(graph_id) {
        var ctx= document.getElementById("chart"+graph_id);
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: json_graph[graph_id]['labels'],
                datasets: [{
                    label: '# of Votes',
                    data: json_graph[graph_id]['votes'],
                    backgroundColor: [
                        'rgba(102, 55, 2, 0.7)',
                        'rgba(130, 73, 7, 0.7)',
                        'rgba(177, 109, 30, 0.7)',
                        'rgba(220, 150, 70, 0.7)',
                        'rgba(241, 190, 133, 0.7)',
                        'rgba(250, 232, 212, 0.7)'
                    ],
                    borderColor: [
                        'rgba(255, 246, 235, 1)',
                        'rgba(255, 246, 235, 1)',
                        'rgba(255, 246, 235, 1)',
                        'rgba(255, 246, 235, 1)',
                        'rgba(255, 246, 235, 1)',
                        'rgba(255, 246, 235, 1)',
                    ],
                    borderWidth: 0.2,
                    hoverBorderWidth: 1.0,
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero:true,
                        }
                    }],
                    xAxes: [{
                        barPercentage: 0.6,
                    }]
                }
            }
        });
    }
})
</script>

<div class="resultField" style="font-family:'나눔스퀘어 Light', serif; background-color: #e0ba8a; padding: 60px 300px;">
    <div class='container' style="background-color: white; padding: 100px; border-radius: 40px;" align='center'>
        <div class="result_titles" style="margin-bottom: 100px;">
            <h1 align="center" class="result_title" style="font-weight: bold; color: #3e2703">{{ survey.title }}</h1><br>
            <hr style="border-color: #af8c53; width: 500px;">
            <p align="center" class="result_subtitle" style="color: #80672a">{{ survey.subtitle }}</p>
            <hr style="border-color: #af8c53; width: 500px;">
        </div>

        {%  for id, field in fields.items  %}
            {%  if field.type == "1" %}
                <div class="container">
                    <p style="font-size: 18px; color: #5b4119; margin: 40px 0px; padding-left: 30px;">ㆍ {{ field.question }} ㆍ</p>
                    <div class="col-lg-12">
                        <div class="row" style="height: 500px;">
                            <div class="col-sm-1"></div>
                            <div class='col-sm-10'>
                                <canvas id='chart{{ id }}' width="500" height="400"></canvas><br>
                            </div>
                            <div class="col-sm-1"></div>
                        </div>
                    </div>
                </div><hr>
            {%  else  %}
                <div class="container" style="text-align: center;">
                    <p style="font-size: 18px; color: #5b4119; margin: 40px 0px; padding-left: 30px;">ㆍ {{ field.question }} ㆍ</p>
                    <div id="list{{ id }}"></div>
                </div><hr>
            {%  endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}

response/templates/response/join_survey.html
{% extends 'layout.html' %}
{%  load static  %}
{% block content %}
    <div class="container" style="font-family: '나눔스퀘어 Light', serif; vertical-align: middle; height: 600px; line-height: 600px; text-align: center;">
        <div class="SurveyComplete" style="background-color: #fbfbfb; display: inline-block; vertical-align: middle; line-height: normal; height: 450px; width: 750px; padding: 50px;">
            <div class="JoinInfo" style="margin-bottom: 30px; font-size: 14px;; padding: 50px 70px 30px 70px;">
                <div class="previewImage" style="margin-bottom: 30px;"><img src="{% static 'response/images/quotation.png' %}" width="30" height="30"></div>
                <h2>{{ survey.title }}</h2>
                <h2> 에 참여해주셔서 감사합니다.</h2>
            </div>
            <div class="JoinButton">
                <a href="{% url 'root' %}" style="background-color: #c4a784; padding: 15px; border-radius: 10px; color: white;">Go Home</a>
                <a href="{% url 'response:result_survey' survey.pk %}" style="background-color: #c4a784; padding: 15px; border-radius: 10px; color: white; display: inline-block; width: 100px;">Result</a>
            </div>
        </div>
{% endblock %}

response/templates/response/layout.html
{% extends 'layout.html' %}
{% load static %}
{% block title %}Survey_Result{% endblock %}
{% block style %}
    <link rel="stylesheet" href="{% static 'response/css/style.css' %}">
{%  endblock %}

response/templates/response/preview.html
{% extends 'layout.html' %}
{%  load static %}

{% block content %}
    <div class="container" style="font-family: '나눔스퀘어 Light', serif; vertical-align: middle; height: 600px; line-height: 600px; text-align: center;">
        <div class="previewTitle" style="background-color: #fbfbfb; display: inline-block; vertical-align: middle; line-height: normal; height: 450px; width: 750px; padding: 50px;">
            <div class="previewImage" style="margin-bottom: 20px;"><img src="{% static 'response/images/quotation.png' %}" width="30" height="30"></div>
            <h1 class="previewTitle" style="margin-bottom: 10px;">{{ survey.title }}</h1>
            <hr style="width: 500px; margin-bottom: 50px;">
            <p class="previewSubtitle" style="color: #333333; margin-bottom: 50px; font-size: 18px;">
                {{ survey.subtitle }}
            </p>
            <p class="previewInfo" style="margin-bottom: 30px; font-size: 14px;">
            작성자: {{ survey.author }}<br><br>
            문항수: {{ survey.field_set.count }}<br></p>
            <div class="previewButton">
                <a href="{% url 'response:response_survey' survey.pk %}" style="background-color: #c4a784; padding: 15px; border-radius: 10px; color: white;">Response</a>
                <a href="{% url 'board:main' %}" style="background-color: #c4a784; padding: 15px; border-radius: 10px; color: white; display: inline-block; width: 100px;">Back</a>
            </div>
        </div>
    </div>
{% endblock %}

response/templates/response/survey.html
{% extends 'layout.html' %}
{% load bootstrap4 %}

{% bootstrap_css %}
{% block content %}
    <div class="container SurveyForm" style="font-family: '나눔스퀘어 Light', serif; margin: auto; margin-top: 80px; margin-bottom: 100px; padding-top: 30px; padding-bottom: 30px; text-align: center; width: 900px; border: 1px solid #d7d7d7; box-shadow: 10px 10px 10px rgba(0,0,0,0.3);">
        <div class="SurveyFormTitleSet" style="display: inline-block;">
            <h1 align="center" style="margin-bottom: 20px; margin-top: 50px;">{{ survey.title }}</h1>
            <hr style="margin-bottom: 50px; width: 400px;">
        </div>
        <form action="" method="post">
        {% csrf_token %}
        <div id="surveyFormFieldSet" style="display: inline-block; width: 900px; padding: 10px 50px;">
            <ul class="surveyFormField">
                {% for field in fields %}
                    <li style="margin-top: 50px; margin-bottom: 20px; font-size: 18px; text-align: left;">{{ forloop.counter }}. {{ field }}</li>
                    {% if field.multiplechoice_set.all %}
                        {% for choice in field.multiplechoice_set.all %}
                            <div class="SurveyFormChoice" style="margin-bottom: 15px; text-align: left;">
                            <input type="radio" name="{{ field.id }}" id="{{ choice.id }}" value="{{ choice.id }}">
                            <label for="{{ choice.id }}">{{ choice.choice_text }}</label></div>
                        {% endfor %}
                    {% else %}
                        <div class="SurveyFormText" align="left">
                            <textarea cols="80" rows="4" id="{{ field.id }}" name="{{  field.id  }}"></textarea>
                            <label for="{{ field.id }}"></label>
                        </div>
                    {% endif %}
                {% endfor %}
            </ul>
            <div class="surveyFormSubmit" align="center" style="margin-top: 100px;">
                <input type="submit" style="background-color: #c4a784; padding: 15px; border-radius: 10px; color: white; display: inline-block; width: 100px; text-align: center; border:none;" value="Submit">
            </div>
        </div>
        </form>
    </div>
{% endblock %}