board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.main, name='main'),
    path('interest/', views.survey_interest, name='survey_interest'),
    path('ongoing/', views.survey_ongoing, name='survey_ongoing'),
    path('answer/', views.survey_participated, name='survey_participated'),
    path('complete/', views.survey_complete, name='survey_complete'),
    path('tag/<int:pk>/', views.survey_tag, name='survey_tag'),
]

branchtown/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', lambda r: redirect('main:mainpage'), name='root'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('board/', include('board.urls', namespace='board')),
    path('main/', include('main.urls', namespace='main')),
    path('response/', include('response.urls', namespace='response')),
    path('survey/', include('survey.urls', namespace='survey')),
    path('tag/', include('tag.urls', namespace='tag')),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.mainpage, name='mainpage'),
    path('/intro/', views.intropage, name='intropage'),
    path('/cs/', views.cspage, name='cspage'),


]

response/urls.py
from django.urls import path
from . import views


app_name = 'response'

urlpatterns = [
    path('result/<int:pk>/', views.ResultView.as_view(), name="result_survey"),
    path('<int:pk>/preview/', views.preview_survey, name='preview_survey'),
    path('<int:pk>/survey/', views.response_survey, name='response_survey'),
    path('<int:pk>/join/', views.join_survey, name='join_survey'),

    # path('<int:pk>/survey/text/', views.response_survey_text, name='response_survey_text')
]

tag/urls.py
from django.urls import path

app_name = 'tag'

urlpatterns = [

]

board/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

board/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from survey.models import Survey
from tag.models import Tag


def main(request):
    surveys = Survey.objects.all().order_by('-id')
    return render(request, 'board/survey_base.html', {
        'category': 'All Survey',
        'surveys': surveys,
    })


@login_required
def survey_interest(request):
    if request.user.is_authenticated:
        tags = request.user.profile.tag.all()
        surveys = Survey.objects.filter(tag__in=tags).distinct()
    else:
        surveys = Survey.objects.none()

    return render(request, 'board/survey_base.html', {
        'category': 'Recommended',
        'surveys': surveys,
    })


def survey_tag(request, pk):
    tag = Tag.objects.get(pk=pk)
    surveys = tag.survey_set.all()
    return render(request, 'board/survey_base.html', {
        'category': tag.name,
        'surveys': surveys,
    })


def survey_ongoing(request):
    surveys = Survey.objects.filter(status='o')
    return render(request, 'board/survey_base.html', {
        'category': 'Ongoing',
        'surveys': surveys,
    })


@login_required()
def survey_participated(request):
    surveys = Survey.objects.filter(response__respondent_id=request.user)
    return render(request, 'board/survey_base.html', {
        'category': 'Participated',
        'surveys': surveys,
    })


def survey_complete(request):
    surveys = Survey.objects.filter(status='c')
    return render(request, 'board/survey_base.html', {
        'category': 'Completed',
        'surveys': surveys,
    })

main/views.py
from django.shortcuts import render, redirect
from survey.models import Survey
from tag.models import Tag


def mainpage(request):
    survey_recent = Survey.objects.all().order_by('-id')
    if request.user.is_authenticated:
        tags = request.user.profile.tag.all()
        survey_interest = Survey.objects.filter(tag__in=tags).distinct()
    else:
        survey_interest = Survey.objects.all().order_by('-id')  # TODO 일단 board.survey_recent.surveys 와 똑같이 설정 추후 변경해야함

    searched_tag = request.GET.get('tag')
    if Tag.objects.filter(name=searched_tag):
        tag = Tag.objects.get(name=searched_tag)
        return redirect('board:survey_tag', tag.pk)

    return render(request, 'main/mainpage.html', {
        'survey_interest': survey_interest,
        'survey_recent': survey_recent,
    })


def intropage(request):
    return render(request, 'main/introduction.html')


def cspage(request):
    return render(request, 'main/cspage.html')

board/templates/board/main.html
{% extends 'layout.html' %}
{% load static %}

{%  block style  %}
    <link rel="stylesheet" href="{% static 'board/css/style.css' %}">
{%  endblock %}

board/templates/board/survey_base.html
{% extends 'board/main.html' %}
{% load static %}

{% block content %}
    <div class="middle_title">
        <p> {{ category }}</p>
    </div>
    <div class="container">
        <div class="row">
            {% for survey in surveys %}
                <div class="col-12 col-md-6 col-lg-4 col-xl-3">
                    <div class="card">
                        <img src="{% static 'board/images/test2.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <div id="board_titles">
                                <p class="card-title">{{ survey.title }}</p>
                                <p class="card-text">{{  survey.subtitle  }}</p>
                            </div>
                            <div id="board_tags">
                            <p>
                                {% for tag in  survey.tag.all %}
                                    <a href="{% url 'board:survey_tag' tag.id %}" style="text-decoration: none">
                                        #{{ tag }}
                                    </a>
                                {% endfor %}
                            </p>
                            </div>
                            <div class="board_buttons">
                            <a href="{% url 'response:preview_survey' survey.id %}" class="response_button">Respond</a>
                            <a href="{% url 'response:result_survey' survey.id %}" class="result_button">View Results</a>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

board/templates/board/survey_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1> 폼에 대한 detail을 보여주는 곳 </h1>
    <h2> {{ survey.id }} 번째 폼에 대한 detail</h2>
    {{ survey.title }} <hr>
    {{ survey.subtitle }}

    <hr>
    <h2> 설문 문항 </h2>
    <ol>
    {% for field in fields %}
        <li>{{ field.question }}</li> <br>
    {% endfor %}
    </ol>
</body>
</html>

board/templates/board/survey_interest.html
{% extends 'board/main.html' %}
{% load static %}

{% block content %}
    <div class="middle_title">
        <b>◈ 추천 설문</b>
    </div>
    <div class="container">
        <div class="row">
            {% for survey in surveys %}
                <div class="col-12 col-md-6 col-lg-4 col-xl-3">
                    <div class="card">
                        <img src="{% static 'images/logo.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ survey.title }}</h5>
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                            <p>
                                {% for tag in  survey.tag.all %}
                                    <a href="{% url 'board:survey_tag' tag.id %}" style="text-decoration: none">
                                        #{{ tag }}
                                    </a>
                                {% endfor %}
                            </p>
                            <a href="{% url 'board:survey_detail' survey.id %}" class="btn btn-primary">설문 응답하기</a>
                            <a href="#">
                                <img src="{% static 'images/share.png' %}" alt="" width="30">
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

board/templates/board/survey_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <h1> form_list page </h1>
    <h2> form_list를 관리하는 페이지. 클릭하면 detail view로 이동</h2>

    <form action="" method="get">
        <input type="text" name="q" />
        <input type="submit" value="검색" />
    </form>


     <table class="table table-hover table-bordered">
         <thead>
         <tr>
             <th>id</th>
             <th>title</th>
             <th>subtitle</th>
             <th>created_at</th>
         </tr>
         </thead>
         {% for form in form_list %}
             <tr>
                 <td>{{ form.id }}</td>
                 <td><a href='{% url "board:survey_detail" form.id %}'>
                     {{ form.title }}
                    </a></td>
                    <td><small>{{ form.subtitle }}</small></td>
                    <td><small>at {{ form.created_at }}</small></td>
             </tr>
         {% endfor %}
     </table>
</body>
</html>

board/templates/board/survey_recent.html
{% extends 'board/main.html' %}
{% load static %}

{% block content %}
    <div class="middle_title">
        <b>◈ 최신 설문</b>
    </div>
    <div class="container">
        <div class="row">
            {% for survey in surveys %}
                <div class="col-12 col-md-6 col-lg-4 col-xl-3">
                    <div class="card">
                        <img src="{% static 'images/logo.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ survey.title }}</h5>
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                            <p>
                                {% for tag in  survey.tag.all %}
                                    <a href="{% url 'board:survey_tag' tag.id %}" style="text-decoration: none">
                                        #{{ tag }}
                                    </a>
                                {% endfor %}
                            </p>
                            <a href="{% url 'board:survey_detail' survey.id %}" class="btn btn-primary">설문 응답하기</a>
                            <a href="#">
                                <img src="{% static 'images/share.png' %}" alt="" width="30">
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

board/templates/board/survey_tag.html
{% extends 'board/main.html' %}
{% load static %}

{% block content %}
    <div class="middle_title">
        <b>◈ {{ tag.name }}</b>
    </div>
    <div class="container">
        <div class="row">
            {% for survey in surveys %}
                <div class="col-12 col-md-6 col-lg-4 col-xl-3">
                    <div class="card">
                        <img src="{% static 'images/logo.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{ survey.title }}</h5>
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                            <p>
                                {% for tag in  survey.tag.all %}
                                    <a href="{% url 'board:survey_tag' tag.id %}" style="text-decoration: none">
                                        #{{ tag }}
                                    </a>
                                {% endfor %}
                            </p>
                            <a href="{% url 'board:survey_detail' survey.id %}" class="btn btn-primary">설문 응답하기</a>
                            <a href="#">
                                <img src="{% static 'images/share.png' %}" alt="" width="30">
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}